### ISSUE TITLE
ssh: connect to host benten.dlab.berkeley.edu port 22: Connection refused

### ISSUE THREAD

**Issue by EastBayEv** [dlab-projects/benten-ml-projects#2]
I have lost my access to benten. Can anybody help me figure out what is going on?

**Comment by jackspaceBerkeley** [comment]
Check to see whether you are on AirBears 2 wifi (Ethernet is even better).

**Comment by ck37** [comment]
Yeah calVisitor will not let you ssh

**Comment by EastBayEv** [comment]
I am indeed on AirBears2. My machine does not have an ethernet port.

**Comment by ck37** [comment]
I just sshed in fine: `ssh ck37@benten.dlab.berkeley.edu`. Sounds like your
DNS might be down/broken - I'd try restarting your wireless connnection.
You could also use a USB -> ethernet adapter, or lightning -> ethernet if
on a mac. Or could it be too many password retry attempts? One last option
is the firewall on your computer is blocking outbound ssh.

**Comment by ck37** [comment]
Please also post the command you are using to connect.

**Comment by EastBayEv** [comment]
ssh evan@benten.dlab.berkeley.edu

**Comment by jackspaceBerkeley** [comment]
Fail2ban might have caught you.  :)  Give me a sec, I'll reset it.  Do you
know your current IP address?

**Comment by ck37** [comment]
Closing, this is old.
